# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

# pylint: disable=R0205,R0902,R0903,R0913,E1101


import g2hasher_pb2 as g2hasher__pb2
import grpc


class G2HasherStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Destroy = channel.unary_unary(
            "/g2hasher.G2Hasher/Destroy",
            request_serializer=g2hasher__pb2.DestroyRequest.SerializeToString,
            response_deserializer=g2hasher__pb2.DestroyResponse.FromString,
        )
        self.ExportTokenLibrary = channel.unary_unary(
            "/g2hasher.G2Hasher/ExportTokenLibrary",
            request_serializer=g2hasher__pb2.ExportTokenLibraryRequest.SerializeToString,
            response_deserializer=g2hasher__pb2.ExportTokenLibraryResponse.FromString,
        )
        self.Init = channel.unary_unary(
            "/g2hasher.G2Hasher/Init",
            request_serializer=g2hasher__pb2.InitRequest.SerializeToString,
            response_deserializer=g2hasher__pb2.InitResponse.FromString,
        )
        self.InitWithConfig = channel.unary_unary(
            "/g2hasher.G2Hasher/InitWithConfig",
            request_serializer=g2hasher__pb2.InitWithConfigRequest.SerializeToString,
            response_deserializer=g2hasher__pb2.InitWithConfigResponse.FromString,
        )
        self.Process = channel.unary_unary(
            "/g2hasher.G2Hasher/Process",
            request_serializer=g2hasher__pb2.ProcessRequest.SerializeToString,
            response_deserializer=g2hasher__pb2.ProcessResponse.FromString,
        )


class G2HasherServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ExportTokenLibrary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def InitWithConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Process(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_G2HasherServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Destroy": grpc.unary_unary_rpc_method_handler(
            servicer.Destroy,
            request_deserializer=g2hasher__pb2.DestroyRequest.FromString,
            response_serializer=g2hasher__pb2.DestroyResponse.SerializeToString,
        ),
        "ExportTokenLibrary": grpc.unary_unary_rpc_method_handler(
            servicer.ExportTokenLibrary,
            request_deserializer=g2hasher__pb2.ExportTokenLibraryRequest.FromString,
            response_serializer=g2hasher__pb2.ExportTokenLibraryResponse.SerializeToString,
        ),
        "Init": grpc.unary_unary_rpc_method_handler(
            servicer.Init,
            request_deserializer=g2hasher__pb2.InitRequest.FromString,
            response_serializer=g2hasher__pb2.InitResponse.SerializeToString,
        ),
        "InitWithConfig": grpc.unary_unary_rpc_method_handler(
            servicer.InitWithConfig,
            request_deserializer=g2hasher__pb2.InitWithConfigRequest.FromString,
            response_serializer=g2hasher__pb2.InitWithConfigResponse.SerializeToString,
        ),
        "Process": grpc.unary_unary_rpc_method_handler(
            servicer.Process,
            request_deserializer=g2hasher__pb2.ProcessRequest.FromString,
            response_serializer=g2hasher__pb2.ProcessResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "g2hasher.G2Hasher", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class G2Hasher(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Destroy(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/g2hasher.G2Hasher/Destroy",
            g2hasher__pb2.DestroyRequest.SerializeToString,
            g2hasher__pb2.DestroyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ExportTokenLibrary(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/g2hasher.G2Hasher/ExportTokenLibrary",
            g2hasher__pb2.ExportTokenLibraryRequest.SerializeToString,
            g2hasher__pb2.ExportTokenLibraryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Init(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/g2hasher.G2Hasher/Init",
            g2hasher__pb2.InitRequest.SerializeToString,
            g2hasher__pb2.InitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def InitWithConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/g2hasher.G2Hasher/InitWithConfig",
            g2hasher__pb2.InitWithConfigRequest.SerializeToString,
            g2hasher__pb2.InitWithConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Process(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/g2hasher.G2Hasher/Process",
            g2hasher__pb2.ProcessRequest.SerializeToString,
            g2hasher__pb2.ProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
