# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import szdiagnostic_pb2 as szdiagnostic__pb2


class SzDiagnosticStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckDatabasePerformance = channel.unary_unary(
                '/szdiagnostic.SzDiagnostic/CheckDatabasePerformance',
                request_serializer=szdiagnostic__pb2.CheckDatabasePerformanceRequest.SerializeToString,
                response_deserializer=szdiagnostic__pb2.CheckDatabasePerformanceResponse.FromString,
                )
        self.PurgeRepository = channel.unary_unary(
                '/szdiagnostic.SzDiagnostic/PurgeRepository',
                request_serializer=szdiagnostic__pb2.PurgeRepositoryRequest.SerializeToString,
                response_deserializer=szdiagnostic__pb2.PurgeRepositoryResponse.FromString,
                )


class SzDiagnosticServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckDatabasePerformance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurgeRepository(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SzDiagnosticServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckDatabasePerformance': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckDatabasePerformance,
                    request_deserializer=szdiagnostic__pb2.CheckDatabasePerformanceRequest.FromString,
                    response_serializer=szdiagnostic__pb2.CheckDatabasePerformanceResponse.SerializeToString,
            ),
            'PurgeRepository': grpc.unary_unary_rpc_method_handler(
                    servicer.PurgeRepository,
                    request_deserializer=szdiagnostic__pb2.PurgeRepositoryRequest.FromString,
                    response_serializer=szdiagnostic__pb2.PurgeRepositoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'szdiagnostic.SzDiagnostic', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SzDiagnostic(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckDatabasePerformance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/szdiagnostic.SzDiagnostic/CheckDatabasePerformance',
            szdiagnostic__pb2.CheckDatabasePerformanceRequest.SerializeToString,
            szdiagnostic__pb2.CheckDatabasePerformanceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PurgeRepository(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/szdiagnostic.SzDiagnostic/PurgeRepository',
            szdiagnostic__pb2.PurgeRepositoryRequest.SerializeToString,
            szdiagnostic__pb2.PurgeRepositoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
