# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: szdiagnostic.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12szdiagnostic.proto\x12\x0cszdiagnostic\"7\n\x1f\x43heckDatabasePerformanceRequest\x12\x14\n\x0csecondsToRun\x18\x01 \x01(\x05\"2\n CheckDatabasePerformanceResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x18\n\x16PurgeRepositoryRequest\"\x19\n\x17PurgeRepositoryResponse2\xed\x01\n\x0cSzDiagnostic\x12{\n\x18\x43heckDatabasePerformance\x12-.szdiagnostic.CheckDatabasePerformanceRequest\x1a..szdiagnostic.CheckDatabasePerformanceResponse\"\x00\x12`\n\x0fPurgeRepository\x12$.szdiagnostic.PurgeRepositoryRequest\x1a%.szdiagnostic.PurgeRepositoryResponse\"\x00\x42s\n\'com.senzing.sz.engine.grpc.SzDiagnosticB\x11SzDiagnosticProtoZ5github.com/senzing-garage/sz-sdk-go-grpc/szdiagnosticb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'szdiagnostic_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\'com.senzing.sz.engine.grpc.SzDiagnosticB\021SzDiagnosticProtoZ5github.com/senzing-garage/sz-sdk-go-grpc/szdiagnostic'
  _globals['_CHECKDATABASEPERFORMANCEREQUEST']._serialized_start=36
  _globals['_CHECKDATABASEPERFORMANCEREQUEST']._serialized_end=91
  _globals['_CHECKDATABASEPERFORMANCERESPONSE']._serialized_start=93
  _globals['_CHECKDATABASEPERFORMANCERESPONSE']._serialized_end=143
  _globals['_PURGEREPOSITORYREQUEST']._serialized_start=145
  _globals['_PURGEREPOSITORYREQUEST']._serialized_end=169
  _globals['_PURGEREPOSITORYRESPONSE']._serialized_start=171
  _globals['_PURGEREPOSITORYRESPONSE']._serialized_end=196
  _globals['_SZDIAGNOSTIC']._serialized_start=199
  _globals['_SZDIAGNOSTIC']._serialized_end=436
# @@protoc_insertion_point(module_scope)
