# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import szproduct_pb2 as szproduct__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in szproduct_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SzProductStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLicense = channel.unary_unary(
                '/szproduct.SzProduct/GetLicense',
                request_serializer=szproduct__pb2.GetLicenseRequest.SerializeToString,
                response_deserializer=szproduct__pb2.GetLicenseResponse.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/szproduct.SzProduct/GetVersion',
                request_serializer=szproduct__pb2.GetVersionRequest.SerializeToString,
                response_deserializer=szproduct__pb2.GetVersionResponse.FromString,
                _registered_method=True)


class SzProductServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLicense(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SzProductServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLicense': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLicense,
                    request_deserializer=szproduct__pb2.GetLicenseRequest.FromString,
                    response_serializer=szproduct__pb2.GetLicenseResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=szproduct__pb2.GetVersionRequest.FromString,
                    response_serializer=szproduct__pb2.GetVersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'szproduct.SzProduct', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('szproduct.SzProduct', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SzProduct(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLicense(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/szproduct.SzProduct/GetLicense',
            szproduct__pb2.GetLicenseRequest.SerializeToString,
            szproduct__pb2.GetLicenseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/szproduct.SzProduct/GetVersion',
            szproduct__pb2.GetVersionRequest.SerializeToString,
            szproduct__pb2.GetVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
