name: publish to pypi

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read

jobs:
  build-distribution:
    name: build distribution
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up Python
        uses: actions/setup-python@v5

      - name: install pypa/build
        run: |
          python -m pip install --upgrade pip
          python -m pip install --requirement requirements.txt
          python -m pip install build

      - name: build a binary wheel and a source tarball
        run: python3 -m build

      - name: store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    environment:
      name: pypi
      url: https://pypi.org/p/senzing-grpc
    if: startsWith(github.ref, 'refs/tags/') # only publish to PyPI on tag pushes
    name: publish Python distribution to PyPI
    needs:
      - build-distribution
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    name: Sign the Python distribution with Sigstore and upload them to GitHub Release
    needs:
      - publish-to-pypi
    permissions:
      contents: write # IMPORTANT: mandatory for making GitHub Releases
      id-token: write # IMPORTANT: mandatory for sigstore
    runs-on: ubuntu-latest

    steps:
      - name: download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl

      - name: upload artifact signatures to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        # Upload to GitHub Release using the `gh` CLI.
        # `dist/` contains the built packages, and the
        # sigstore-produced signatures and certificates.
        run: gh release upload '${{ github.ref_name }}' dist/** --repo '${{ github.repository }}'
