name: pytest darwin

on: [pull_request, workflow_dispatch]

env:
  PYTHONPATH: /Users/runner/work/sz-sdk-python-grpc/sz-sdk-python-grpc/src

permissions:
  contents: read

jobs:
  pytest-darwin:
    name: "pytest OS: ${{ matrix.os }}; Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        # 3.9 is unsupported on the darwin runner
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv ./venv
          source ./venv/bin/activate
          echo "PATH=${PATH}" >> "${GITHUB_ENV}"
          python -m pip install --upgrade pip
          python -m pip install --requirement requirements.txt
          python -m pip install psutil pytest pytest-cov pytest-schema

      - if: matrix.python-version == '3.10'
        name: Install python libraries for python 3.10
        run: |
          source ./venv/bin/activate
          python -m pip install typing_extensions

      - name: Install Docker
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12

      - name: Run gRPC service
        run: docker run --detach --env SENZING_TOOLS_ENABLE_ALL --publish 8261:8261 senzing/serve-grpc:latest

      - name: Run pytest on tests
        run: |
          source ./venv/bin/activate
          pytest tests/ --verbose --capture=no --cov=src/senzing_grpc

      - name: Rename coverage file
        env:
          COVERAGE_FILE: "coverage.${{ matrix.python-version }}"
        run: |
          mv .coverage "$COVERAGE_FILE"

      - name: Store coverage file
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.${{ matrix.python-version }}

  coverage:
    name: Coverage
    needs: pytest-darwin
    permissions:
      pull-requests: write
      contents: write
    uses: senzing-factory/build-resources/.github/workflows/python-coverage-comment.yaml@v2
